#!/usr/bin/env python3
"""
compare_scans.py — Compare scan-before and scan-after results.

Usage:
    python scripts/compare_scans.py artifacts/scan-before artifacts/scan-after > artifacts/scan-after/comparison.md

This script reads JSON reports from both scan directories and produces
a comparison summary showing which findings appeared, disappeared, or remained.
"""

import json
import os
import sys


def load_json_safe(filepath):
    """Load a JSON file, returning empty dict/list on failure."""
    try:
        with open(filepath) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"Warning: Could not load {filepath}: {e}", file=sys.stderr)
        return {}


def count_bandit_findings(data):
    """Count Bandit findings from JSON output."""
    if isinstance(data, dict) and 'results' in data:
        return len(data['results'])
    return 0


def count_semgrep_findings(data):
    """Count Semgrep findings from JSON output."""
    if isinstance(data, dict) and 'results' in data:
        return len(data['results'])
    return 0


def count_pip_audit_findings(data):
    """Count pip-audit findings."""
    if isinstance(data, list):
        return sum(len(dep.get('vulns', [])) for dep in data if 'vulns' in dep)
    if isinstance(data, dict) and 'dependencies' in data:
        return sum(
            len(dep.get('vulns', []))
            for dep in data['dependencies']
            if 'vulns' in dep
        )
    return 0


def count_gitleaks_findings(data):
    """Count Gitleaks findings."""
    if isinstance(data, list):
        return len(data)
    return 0


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <scan-before-dir> <scan-after-dir>")
        sys.exit(1)

    before_dir = sys.argv[1]
    after_dir = sys.argv[2]

    tools = {
        'bandit': ('bandit.json', count_bandit_findings),
        'semgrep': ('semgrep.json', count_semgrep_findings),
        'pip-audit': ('pip-audit.json', count_pip_audit_findings),
        'gitleaks': ('gitleaks.json', count_gitleaks_findings),
    }

    print("# Scan Comparison: Before vs After")
    print()
    print("| Tool | Before | After | Delta |")
    print("|------|--------|-------|-------|")

    for tool_name, (filename, counter) in tools.items():
        before_data = load_json_safe(os.path.join(before_dir, filename))
        after_data = load_json_safe(os.path.join(after_dir, filename))

        before_count = counter(before_data)
        after_count = counter(after_data)
        delta = after_count - before_count

        delta_str = f"+{delta}" if delta > 0 else str(delta)
        print(f"| {tool_name} | {before_count} | {after_count} | {delta_str} |")

    print()
    print("---")
    print("Generated by compare_scans.py")


if __name__ == '__main__':
    main()
